[general]
import = [ "main.toml" ]

[env]
BGMODE = "dark"

# font

    [font]
    size = 16.0

    [font.offset]
    x = 0 # spaces between chars
    y = 0 # spaces between lines

    [font.glyph_offset]
    x = 0
    y = 0

    [font.normal]
    family = "3270 Nerd Font Mono"
    style = "Regular"

# colors

    [colors]
    draw_bold_text_with_bright_colors = true

    [colors.primary]
    background = "0x073642"
    foreground = "0xfdf6e3"

    [colors.cursor]
    cursor = "0xff1cac"
    text = "0xfdf6e3"

    [colors.normal]
    black   = "0x073642"
    blue    = "0x268bd2"
    cyan    = "0x2aa198"
    green   = "0x859900"
    magenta = "0xd33682"
    red     = "0xdc322f"
    white   = "0xeee8d5"
    yellow  = "0xb58900"

    [colors.bright]
    black   = "0x002b36"
    blue    = "0x839496"
    cyan    = "0x93a1a1"
    green   = "0x586e75"
    magenta = "0x6c71c4"
    red     = "0xcb4b16"
    white   = "0xfdf6e3"
    yellow  = "0x657b83"

